### ISSUE TITLE
Istio ingress vs ingress-gce

### ISSUE THREAD

**Issue by flexlee** [thesandlord/Istio101#2]
Is Istio ingress different from GKE(GCE) ingress? It seems Istio ingress ignores other annotations like `kubernetes.io/ingress.global.static-ip-name`. Can it be replaced with the default GKE ingress? Thanks.

**Comment by thesandlord** [comment]
Yes, Istio ingress is different than GCLB ingress. AFAIK it can't be replaced with the GCLB ingress (yet!), I think there is work being done so the GCLB will work with Istio out of the box, but I'm not sure.

**Comment by flexlee** [comment]
Thanks for the answer. In your demo, can the Istio ingress be replaced by GCLB? It doesn't seem to be doing anythig special other than routing traffic to frontend service. I'm trying the GCLB for my fork but it seems I'm hitting the GKE service quota - the `make delete-cluster` doesn't seem to clean up all the artifacts.

**Comment by thesandlord** [comment]
It actually does do something special, it adds the trace headers to each request and it allows the retry logic to work for the frontend. You could potentially put the Istio ingress behind the GCLB ingress, but I haven't tried that.

`make delete-clusters` should delete everything, the fact that it is not is an issue. Do you have a list of what it leaves behind?

**Comment by flexlee** [comment]
@thesandlord Interesting. I will try putting GCLB in front of istio-ingress.

never mind with `delete-clusters`. I think I commented out the `delete istio-ingress` and `svc` statements at one point and recreated the clusters. So there was some ingress and services instances left dangling. I ended up manually deleting them in GC console. Thanks for the help
