### ISSUE TITLE
Error: "frontend-route" already exists

### ISSUE THREAD

**Issue by TheFirstAvenger** [thesandlord/Istio101#3]
When attempting to run `./istio-0.6/bin/istioctl create -f ./configs/istio/routing-2.yaml`
the following error occurs: `Error: routerules.config.istio.io "frontend-route" already exists`

**Comment by TheFirstAvenger** [comment]
I ran delete-route-rules between routing-1.yml and routing-2.yml. @thesandlord is updating the instructions to add this step the correct resolution?

**Comment by thesandlord** [comment]
Closing because of all the changes with Istio 1.0 (i.e RouteRules don't exist anymore)
